apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-webapp
  name: hello-webapp
  namespace: webapp
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: hello-webapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-webapp
    spec:
      containers:
      - image: docker.io/library/hello-webapp:latest
        name: hello-webapp
        ports:
        - name: metrics
          containerPort: 8080
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
