apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-webapp
  name: hello-webapp
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-webapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-webapp
    spec:
      containers:
      - image: docker.io/library/hello-webapp:latest
        imagePullPolicy: IfNotPresent
        name: hello-webapp
        ports:
        - name: metrics
          containerPort: 8080
