apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-webapp
  name: hello-webapp
  namespace: webapp
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-webapp
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
